export const addons = [
  {
    id: 1,
    name: "Add a 16 inches number foil",
    description: "Add a 16-inch Number Foil for a Bigger Celebration!",
    price: 150,
    type: "toggle",
    src: "/images/addons/numberFoil.jpg",
  },
  {
    id: 2,
    name: "Add a hbd Cake Foil",
    description: "Add a happy birthday Cake Foil for your decoration.",
    price: 200,
    type: "toggle",
    src: "/images/addons/hbdCakefoil.jpg",
  },
  {
    id: 3,
    name: "Add a Crown foil",
    description: "Add a Crown foil for your Decoration",
    price: 200,
    type: "cart",
    src: "/images/addons/crownFoil.jpg",
  },
  {
    id: 4,
    name: "Big Balloon With Confetti",
    description:
      "Add a big balloon with confetti to make your decor more attractive.",
    price: 150,
    type: "cart",
    src: "/images/addons/balloonCon.jpg",
  },
  {
    id: 5,
    name: "Add Name Buntings",
    description: "Add a customised name Buntings.",
    price: 320,
    type: "toggle",
    src: "/images/addons/buntings.jpg",
  },
  {
    id: 6,
    name: "Happy Birthday bunting",
    description: "Happy Birthday bunting.",
    price: 150,
    type: "toggle",
    src: "/images/addons/hbdbunting.jpg",
  },
  {
    id: 7,
    name: "Happy Birthday foil",
    description: "Add Happy birthday foil with varities of color available",
    price: 180,
    type: "toggle",
    src: "/images/addons/hbdfoil.jpg",
  },
  {
    id: 8,
    name: "One Box",
    description: "Add a one box to make your decor more attractive.",
    price: 450,
    type: "toggle",
    src: "/images/addons/oneBox.jpg",
  },
  {
    id: 9,
    name: "Baby Box",
    description: "Add a Baby Box to make your decor more attractive",
    price: 500,
    type: "toggle",
    src: "/images/addons/babybox.jpg",
  },
  {
    id: 10,
    name: "Theme Foils",
    description:
      "Add a theme foil as per theme to make your decor more attractive.",
    price: 300,
    type: "cart",
    src: "/images/addons/themeFoil.jpg",
  },
  {
    id: 11,
    name: "Name Pillar ",
    description:
      "Add a name pillar up to 8 charector to make your decor more attractive.",
    price: 650,
    type: "toggle",
    src: "/images/addons/namePiller.jpg",
  },
  {
    id: 12,
    name: "White cloth with Stand Rental",
    description:
      "Add a white cloth and stand to make your decor more attractive",
    price: 1500,
    type: "toggle",
    src: "/images/addons/stand&cloth.jpg",
  },
  {
    id: 13,
    name: "Background Ring Stand Rental",
    description: "Add a Ring Stand to make your decor more attractive.",
    price: 1000,
    type: "toggle",
    src: "/images/addons/ringStand.jpg",
  },
  {
    id: 14,
    name: "Add a rental Led Digit",
    description: "Add a wooden Led Digit to your decoration.",
    price: 1800,
    type: "toggle",
    src: "/images/addons/ledDigit.jpg",
  },
  {
    id: 15,
    name: "24 Printed Photos",
    description: "24 Printed Photos hanged via ribbons from balloons",
    price: 400,
    type: "toggle",
    src: "/images/addons/printedPics24.jpg",
  },
  {
    id: 16,
    name: "Add 25 Balloons",
    description: "Add 15 balloons to the ceiling and 10 balloons floor ",
    price: 150,
    type: "cart",
    src: "/images/addons/ballons25.jpg",
  },
  {
    id: 17,
    name: "Add a Entrance Balloon Arch",
    description: "Add Entrance balloon Arch ( 220 balloons)",
    price: 1600,
    type: "toggle",
    src: "/images/addons/EntranceBalloonarch.jpg",
  },
  {
    id: 19,
    name: "Add 360 degree selfie Booth Rental",
    description:
      "1 coordinator to guide the kids or guests setup will be available for 4 hours.",
    price: 8000,
    type: "toggle",
    src: "/images/addons/selfiebooth360.jpg",
  },
  {
    id: 20,
    name: "Photo Booth Frame (As per theme)",
    description:
      "Add Themed handy selfie photo Booth to make it more vibrant ( 3×2 ft) ",
    price: 1000,
    type: "toggle",
    src: "/images/addons/photoboothframe.jpg",
  },
  {
    id: 21,
    name: "As per Theme Balloon pillar",
    description:
      "Add theme balloon pillar to look more vibrant. ( 40 balloons )",
    price: 400,
    type: "cart",
    src: "/images/addons/balloonPiller.jpg",
  },
  {
    id: 22,
    name: "Add fairy light",
    description: "Add 1 fairy lights ( 8 meters long) to light up your decor",
    price: 150,
    type: "cart",
    src: "/images/addons/fairtlight.jpg",
  },
  {
    id: 23,
    name: "Happy Birthday Neon light Rental",
    description: "Add a happy Birthday Neon light to make it more vibrant.",
    price: 800,
    type: "toggle",
    src: "/images/addons/hbdneonlight.jpg",
  },
  {
    id: 24,
    name: "Alphabet Led Letter( 9 inches)",
    description:
      "Add the quantity of led letters based on the numbers of alphabets in the name.",
    price: 250,
    type: "cart",
    src: "/images/addons/alphaLed.jpg",
  },
  {
    id: 25,
    name: "As per theme photo props",
    description:
      "Add as per theme photo props make it child decor more attractive.",
    price: 300,
    type: "cart",
    src: "/images/addons/photoprops.jpg",
  },
  {
    id: 26,
    name: "Cake table props rental",
    description:
      "Add cake table props rental make it more attractive ( paper stand, led names, cake stand, suitcase props flower props ).",
    price: 1000,
    type: "toggle",
    src: "/images/addons/caketablewithprops.jpg",
  },
  {
    id: 27,
    name: "Name foil balloon 16inch",
    description:
      "Add a name foil to make your decor more attractive ( max 8 charector) .",
    price: 300,
    type: "cart",
    src: "/images/addons/namefoil16inch.jpg",
  },
  {
    id: 28,
    name: "Add background Stand Rental",
    description: "Add a background stand 6ft to 8ft.",
    price: 800,
    type: "toggle",
    src: "/images/addons/stand.jpg",
  },
  {
    id: 29,
    name: "Welcome Board Rental as per theme ",
    description: "Add a welcome board as per theme to make it more vibrant.",
    price: 2000,
    type: "toggle",
    src: "/images/addons/welcomeboard.jpg",
  },
  {
    id: 30,
    name: "As per theme chalk board Rental",
    description: "Add a chalk board as per theme to look more vibrant ",
    price: 2000,
    type: "toggle",
    src: "/images/addons/chalkboard.jpg",
  },
  {
    id: 31,
    name: "Rent on cake Table and Cake stand",
    description:
      "Add a cake table and cake stand make it more beautiful decor.",
    price: 800,
    type: "toggle",
    src: "/images/addons/caketable.jpg",
  },
  {
    id: 32,
    name: "As per Theme Cutouts",
    description:
      "Add a Theme Cutouts as per theme to look more attractive ( 3*2) .",
    price: 1000,
    type: "toggle",
    src: "/images/addons/Cutouts.jpg",
  },
  {
    id: 33,
    name: "Add 2 star Foil balloon",
    description:
      "Add 2 silver foil balloon to make look more vibrant.( 18 inch)",
    price: 99,
    type: "toggle",
    src: "/images/addons/starfoil.jpg",
  },
  {
    id: 34,
    name: "Add 2 frill curtains",
    description: "Add 2 frill curtains for background it's more look vibrant.",
    price: 250,
    type: "toggle",
    src: "/images/addons/frillcurtains.jpg",
  },
  {
    id: 35,
    name: "Add a rental Led Digit one",
    description: "Add a wooden Led Digit to your decoration.",
    price: 1000,
    type: "cart",
    src: "/images/addons/ledLight.jpg",
  },
];

